---
- name: "MinIO | MinIO env config"
  ansible.builtin.template:
    dest: /etc/default/minio
    src: minio.env.j2
    owner: "{{minio_user}}"
    group: "{{minio_group}}"
  notify:
  - restart minio

- name: "MinIO | MinIO systemd config"
  ansible.builtin.template:
    dest: /etc/systemd/system/minio.service
    src: minio.service.j2
  notify:
  - reload systemd
  - restart minio

- name: MinIO | Ensure services is enabled
  service:
    name: minio
    enabled: yes

- name: MinIO | setcap cap_net_bind_service=+ep 
  shell: "setcap cap_net_bind_service=+ep {{minio_bin_path}}//minio"

- ansible.builtin.meta: flush_handlers

- name: MinIO | Set local alias
  shell: "/usr/local/bin/mc alias set {{minio_mc_alias}} http://127.0.0.1:{{minio_port}} {{minio_root_user}} {{minio_root_password}}"
  register: output
  changed_when: False