---
- name: MinIO | Create group
  group:
    name: "{{minio_group}}"
    system: true
    state: present

- name: MinIO | Create user
  user:
    name: "{{minio_user}}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{minio_group}}"
    create_home: true
    home: "{{ minio_home }}"

- name: MinIO | filesystem on minio data disks
  community.general.filesystem:
    fstype: "{{ item.fstype }}"
    dev: "{{ item.disk }}"
    opts: "-L {{minio_disk_label_prefix}}{{ index + 1 }}"
  with_items: "{{ minio_disks }}"
  loop_control:
    index_var: index

- name: MinIO | Mount up device by label
  ansible.posix.mount:
    path: "{{minio_home}}/{{minio_disk_label_prefix}}{{ index + 1 }}"
    src: "LABEL={{minio_disk_label_prefix}}{{ index + 1 }}"
    passno: 2
    fstype: "{{ item.fstype }}"
    opts: defaults,noatime
    state: mounted
  with_items: "{{ minio_disks }}"
  loop_control:
    index_var: index

- name: 'MinIO | Chown dirs'
  file:
    path: "{{minio_home}}/{{minio_disk_label_prefix}}{{ index + 1 }}"
    state: directory
    owner: "{{minio_user}}"
    group: "{{minio_group}}"
    mode: 0755
  with_items: "{{ minio_disks }}"
  loop_control:
    index_var: index

- name: MinIO | Download MinIO binary
  local_action:
    module: get_url
    url: "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.{{minio_version}}"
    dest: "{{local_tmp}}/minio.{{minio_version}}"
    checksum: sha256:https://dl.min.io/server/minio/release/linux-amd64/archive/minio.{{minio_version}}.sha256sum
  run_once: true
  become: false

- name: MinIO | Download MinIO Client binary
  local_action:
    module: get_url
    url: "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.{{minio_client_version}}"
    dest: "{{local_tmp}}/mc.{{minio_client_version}}"
    checksum: sha256:https://dl.min.io/client/mc/release/linux-amd64/archive/mc.{{minio_client_version}}.sha256sum
  run_once: true
  become: false

- name: 'MinIO | Bin dir'
  file:
    path: "{{minio_bin_path}}"
    state: directory
    owner: "{{minio_user}}"
    group: "{{minio_group}}"
    mode: 0755

- name: "MinIO | Copy MinIO binary"
  ansible.builtin.copy:
    src: "{{local_tmp}}/minio.{{minio_version}}"
    dest: "{{minio_bin_path}}/minio"
    mode: +x
    owner: "{{minio_user}}"
    group: "{{minio_group}}"

- name: "MinIO | Copy MinIO Client binary"
  ansible.builtin.copy:
    src: "{{local_tmp}}/mc.{{minio_client_version}}"
    dest: "{{minio_bin_path}}/mc"
    mode: +x
    owner: "{{minio_user}}"
    group: "{{minio_group}}"

- name: MinIO | Create bin links
  file:
    src: "{{minio_bin_path}}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    state: link
    owner: "{{minio_user}}"
    group: "{{minio_group}}"
    mode: +x
  with_items:
    - minio
    - mc