---
- name: "pre | Install EPEL"
  ansible.builtin.package:
    name: epel-release

- name: "pre | Python librarys"
  ansible.builtin.package:
    name:
    - python3-botocore
    - python3-boto3

- name: "pre | XFS"
  ansible.builtin.package:
    name: xfsprogs

- name: MinIO | Setting fact minio_disks_count
  ansible.builtin.set_fact: minio_disks_count="{{ minio_disks|length }}"
