---
- name: restart minio
  shell: systemctl restart minio &
  delegate_to: "{{ item }}"
  with_items: "{{ groups['all'] }}" # restart all minio
  run_once: True

- name: reload systemd
  systemd:
    daemon_reload: True
